export const projectPartnersList = [
  '/assets/projectPartners/Arbur_logo.png',
  '/assets/projectPartners/Brinkhaus_logo.png',
  '/assets/projectPartners/CONCIRCLE_logo_4C_500px.png',
  '/assets/projectPartners/craftworks_logo.png',
  '/assets/projectPartners/EITM_Central_logo.png',
  '/assets/projectPartners/EITM_East_logo.png',
  '/assets/projectPartners/exoscale_logo.png',
  '/assets/projectPartners/Heller_logo.png',
  '/assets/projectPartners/IGH Infotec AG Logo.png',
  '/assets/projectPartners/MTU Aero Engines_logo.jpg',
  '/assets/projectPartners/Pilotfabrik Industrie 4.0. TU Wien_logo.png',
  '/assets/projectPartners/plasser-and-theurer_logo.png',
  '/assets/projectPartners/PTW_Logo.png',
  '/assets/projectPartners/Software_AG.png',
  '/assets/projectPartners/STARK Spannsysteme GmbH_logo.png',
  '/assets/projectPartners/WFL_logo.jpg',
];
